on: [push]

jobs:
  terrascan_terraform_job:
    runs-on: ubuntu-latest
    name: terrascan-terraform
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan for terraform
      id: terrascan
      uses: accurics/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        only_warn: true
        sarif_upload: true
        iac_dir: 'terraform'
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: terrascan.sarif
  terrascan_cft_job:
    runs-on: ubuntu-latest
    name: terrascan-cft
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan for cft
      id: terrascan
      uses: accurics/terrascan-action@main
      with:
        iac_type: 'cft'
        only_warn: true
        sarif_upload: true
        iac_dir: 'cft'
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: terrascan.sarif
    - name: Run KICS Scan
      continue-on-error: true
      run: |
       sudo mkdir $GITHUB_WORKSPACE/scan_output
       sudo chmod -R a+rwx $GITHUB_WORKSPACE/scan_output
       docker pull checkmarx/kics:latest
       docker run -u $UID:$GID -v $PWD:/$GITHUB_WORKSPACE checkmarx/kics:ubi8 scan -p $GITHUB_WORKSPACE/terraform,$GITHUB_WORKSPACE/cft  --report-formats "all" --ignore-on-exit "all" -o /$GITHUB_WORKSPACE/scan_output -v
     #  echo "Remediating issues"
     #  docker run -u $UID:$GID -v $PWD:/$GITHUB_WORKSPACE checkmarx/kics:ubi8 remediate --include-ids "all" --results "${GITHUB_WORKSPACE}/scan_output/results.json" -v
